### ISSUE TITLE
Cannot read property 'insertBefore' of undefined

### ISSUE THREAD

**Issue by Meaxis** [halfmoonui/halfmoon#24]
I wanted to use Sticky Alerts, but I got an error. Here's what I got:
**Cannot read property 'insertBefore' of undefined TypeError: Cannot read property 'insertBefore' of undefined
    at Object.initStickyAlert**

My code: 
```js
halfmoon.initStickyAlert({
	content: 'Eeee'+result['message'],
	title: "Error "+result['code']+"!",
	alertType: "alert-danger",
	fillType: "filled-lm",
	hasDismissButton: false,
	timeShown: 10000
});
```

In my HTML, I have the StickyAlerts.
```html
<!-- Page wrapper -->
	<div class="page-wrapper text-center">
		<!-- This parent container is required -->
  		<div class="sticky-alerts"></div>
```

**Comment by halfmoonui** [comment]
I went over to www.gethalfmoon.com/docs and pasted your code in the browser. This code: 

`
result = {
    'message': 'Not found',
    'code': '404'
};
halfmoon.initStickyAlert({
	content: 'Eeee'+result['message'],
	title: "Error "+result['code']+"!",
	alertType: "alert-danger",
	fillType: "filled-lm",
	hasDismissButton: false,
	timeShown: 10000
});
`
The code worked and a toast was generated. Are you sure you are importing `halfmoon.js` properly in a script tag?

**Comment by ranabirbasu12** [comment]
Could you, maybe share a link of your website (if it has been hosted anywhere)?

**Comment by Meaxis** [comment]
@halfmoonui Yes, I referenced Halfmoon in the <head> tag of my website.
@ranabirbasu12 No, it's still an HTML file. I could put it online if needed.

**Comment by Meaxis** [comment]
Fixed by referencing Halfmoon at the bottom of the `<body>` tag.

**Comment by MuhsinFatih** [comment]
@Meaxis I tried referencing Halfmoon at the bottom of the <body> tag but I'm still getting the same error. Can you elaborate? I feel like I'm missing something

**Comment by Meaxis** [comment]
GitHub removed bare HTML tags I think. I referenced halfmoon.js in the `<head>` element and in the bottom of the `body` element.

**Comment by MuhsinFatih** [comment]
Nevermind! I am incapable of reading the docs! :D
A quick debugging made me realize I'm missing the required `sticky-alerts` div:
```
<div class="sticky-alerts"></div>
```

**Comment by Meaxis** [comment]
Oh, thought you didn't understand what I said because I mostly read replies in email and comment back on GitHub (so no markdown). 

Glad I may have helped!

**Comment by MuhsinFatih** [comment]
Ah, hahah no you are right. Initially I was asking for clarification, but turns out I was just missing that div
